Changes corresponding to TAT environment changes
The commit to the TAT project labeled:
"Enhancements to bin/runprod, rundev" required changes to 'startmas' and
test_setup.rb: startmas was moved from ./test to ./bin and now uses
the env. var. MAS_RUNDIR, set by .env in TAT, as the directory in which
to run the mas server.  test_setup.rb needed to change to find startmas in
bin instead of test directory.

diff --git a/bin/startmas b/bin/startmas
--- a/bin/startmas
+++ b/bin/startmas
@@ -19,20 +19,22 @@ start_mas_server() {
     $exe -b -f , $p *.txt&
 }
 
-if [ -z "$TATDEV" ]; then
-    echo "Error: TATDEV env. var. not set" >&2
+if [ -z "$TATDEV" -a -z "$MAS_RUNDIR" ]; then
+    echo "Error: TATDEV and MAS_RUNDIR env. vars. not set" >&2
     exit 42
 fi
-cd $TATDEV/library/test/masdev || {
-    echo "Could not cd to MAS dev/run directory - aborting ..." >&2
+if [ -z "$MAS_RUNDIR" ]; then
+    MAS_RUNDIR=$TATDEV/library/test/masdev
+fi
+
+cd $MAS_RUNDIR || {
+    echo "Could not cd to $MAS_RUNDIR - aborting ..." >&2
     exit 43
 }
-script_path=$(dirname $0)
 pgrep_opts='-laf'
 if lsb_release -a 2>/dev/null|egrep -qi 'ubuntu'; then
     pgrep_opts='-lf'
 fi
-cd $script_path >/dev/null
 ports=$(for p in 5441 5442 5443 5444; do echo $p;done|sort -u)
 exe=mas
 if [ $# -gt 0 ]; then
