id -> event_id, test fixes, ...
MasCommunicationServices, test_mas_client.rb: Small change in the
TradableAnalyzer model: id attribute changed to event_id.

runtests: Made the script a little more robust, ...

startmas: Changed the MAS server mode for testing/development to
file mode (with the new feature to retrieve data via external
script) instead of -w/web mode.

hide_tradable_analyzer.rb, test_mas_client.rb: The tests depend
on a TradableAnalyzer class, but the app's actual
TradableAnalyzer is an ActiveRecord class (in
../app/models/tradable_analyzer.rb), which this "MAS/TAT library"
should not depend on, so a dummy TradableAnalyzer was created and
placed in hide_tradable_analyzer.rb - not in tradable_analyzer.rb
because that causes conflicts (i.e., the app tests [../app/] were
loading this test/tradable_analyzer.rb [when it, at first, had
that name] instead of the ActiveRecord one in ../app/models).

diff --git a/test/runtests b/test/runtests
--- a/test/runtests
+++ b/test/runtests
@@ -1,7 +1,60 @@
 #!/bin/bash
 # vim: expandtab:
 
+# Ugly hack to restore (unhide) tradable_analyzer.rb, which may have been
+# renamed to fix the main app test - re. rails confusion about which
+# tradable_analyzer.rb file to use.
+restore_tradable_ana() {
+    real_name=tradable_analyzer.rb
+    hidden_name=hide_tradable_analyzer.rb
+    dir="$1"
+    pushd $dir || return
+    if [ -e $real_name ]; then
+        pushd
+        return  # File name is correct.
+    fi
+    if [ -e $hidden_name ]; then
+        mv $hidden_name $real_name
+    else
+        echo "Fatal error: Could not find *$real_name" >&2
+        exit 43
+    fi
+    pushd
+}
+
+rehide_tradable_ana() {
+    real_name=tradable_analyzer.rb
+    hidden_name=hide_tradable_analyzer.rb
+    dir="$1"
+    pushd $dir || return
+    mv $real_name $hidden_name || {
+        echo "Failed to rehide $real_name" >&2
+    }
+    pushd
+}
+
+script_name=test_mas_client.rb
+found_script=true
+export RUBYLIB='$PWD/../utility:$PWD/../app/mas_bridge'
 iterations=1
+test_script=$(find . -name $script_name)
+if [ -z "$test_script" ]; then
+    if [ -z "$TATDEV" ]; then
+        found_script=false
+        echo "TATDEV env. var. not set." >&2
+    else
+        test_script=$(find $TATDEV -name $script_name)
+        if [ -z "$test_script" ]; then
+            found_script=false
+        fi
+    fi
+fi
+if ! eval $found_script; then
+    echo "Could not find test script $script_name" >&2
+    exit 42
+fi
+testdir=$(dirname $test_script)
+#restore_tradable_ana $testdir
 
 if [ $# -gt 0 ]; then iterations=$1; fi
 if [ $iterations -lt 1 ]; then exit 0; fi
@@ -14,12 +67,13 @@ filter() {
 i=1
 exit_status=0
 time while [ $i -le $iterations ]; do
-    ruby --verbose test/test_mas_client.rb --verbose 2>&1|filter
+    ruby $test_script --verbose 2>&1
     run_status=$?
     if [ $exit_status == 0 ]; then
         exit_status=$run_status
     fi
     ((++i))
 done
+#rehide_tradable_ana $testdir
 if [ $exit_status != 0 ]; then banner FAILED; else banner GOOD; fi
 exit $exit_status
diff --git a/test/startmas b/test/startmas
--- a/test/startmas
+++ b/test/startmas
@@ -2,15 +2,20 @@
 # Start the mas server for testing.
 # vi: expandtab
 
+if [ -z "$TATDEV" ]; then
+    echo "Error: TATDEV env. var. not set" >&2
+    exit 42
+fi
+cd $TATDEV/library/test/masdev || {
+    echo "Could not cd to MAS dev/run directory - aborting ..." >&2
+    exit 43
+}
 script_path=$(dirname $0)
 pgrep_opts='-laf'
 if lsb_release -a 2>/dev/null|egrep -qi 'ubuntu'; then
     pgrep_opts='-lf'
 fi
 cd $script_path >/dev/null
-if [ -z "$MASPORT" ]; then
-    . ./.env
-fi
 ports=$(for p in $MASPORT 5441 5442 5443 5444; do echo $p;done|sort -u)
 exe=mas
 if [ $# -gt 0 ]; then
@@ -23,5 +28,5 @@ fi
 if pgrep $pgrep_opts "mas *-b.*$MASPORT" >/dev/null; then exit 0; fi
 if pgrep $pgrep_opts "masx.*-b.*$MASPORT" >/dev/null; then exit 0; fi
 if pgrep $pgrep_opts "oldmas *-b.*$MASPORT" >/dev/null; then exit 0; fi
-$exe -b -w -f , $ports&
+$exe -b -f , $ports *.txt&
 sleep 1 # Give the server a chance to start-up/initialize.
